ArNetworking: ArServerDataProvider< C, T > Class Template Reference
ArServerDataProvider< C, T > Class Template Reference
Tool to easily obtain and provide changing data values from an acessor method of a class.
#include <ArServerDataProvider.h>
Public Member Functions
ArServerDataProvider (ArServerBase *server, const char *name, const char *description, ArRetFunctor< T > *accessFunctor, ArFunctor *lockFunctor=NULL, ArFunctor *unlockFunctor=NULL)
If this constructor is used, then access data by invoking the accessFunctor ArRetFunctor<T> object.
ArServerDataProvider (ArServerBase *server, const char *name, const char *description, C *obj, T(C::*method)(void), void(C::*lockMethod)(void)=NULL, void(C::*unlockMethod)(void)=NULL)
If this constructor is used, then access data by calling method on object instance obj.
ArServerDataProvider (ArServerBase *server, const char *name, const char *description, C *obj, T(C::*method)(void) const, void(C::*lockMethod)(void)=NULL, void(C::*unlockMethod)(void)=NULL)
If this constructor is used, then access data by calling method on object instance obj.
virtual ~ArServerDataProvider ()
Detailed Description
template<class C, typename T>
class ArServerDataProvider< C, T >
Tool to easily obtain and provide changing data values from an acessor method of a class.
The data item is added to the server, and when clients make requests, this object will call a lock method on a target object (if provided), then obtain a value to reply with by calling the given accessor method on the target object, then call the unlock method (if provided). You can supply these methods either as function pointers (within the class of the target object), or ArFunctor objects.
Client programs can use ArClientDataReceiver to request and receive updates on the value.
Note
This object must remain in scope and not be destroyed to remain active. If this object is deleted (explicitly or if execution leaves scope in which the object was created) then the data item is removed from the server and clients will no longer receive updates.
Replies with data are sent via TCP.
See also
ArClientDataReceiver
Since
2.9.3
Constructor & Destructor Documentation
template<class C, typename T> ArServerDataProvider< C, T >::ArServerDataProvider (ArServerBase * server, const char * name, const char * description, ArRetFunctor< T > * accessFunctor, ArFunctor * lockFunctor = NULL, ArFunctor * unlockFunctor = NULL) inline
If this constructor is used, then access data by invoking the accessFunctor ArRetFunctor<T> object.
If lockFunctor and unlockFunctor are provided (not NULL), then these are invoked before and after invoking accessFunctor.
template<class C, typename T> ArServerDataProvider< C, T >::ArServerDataProvider (ArServerBase * server, const char * name, const char * description, C * obj, T(C::*)(void) method, void(C::*)(void) lockMethod = NULL, void(C::*)(void) unlockMethod = NULL) inline
If this constructor is used, then access data by calling method on object instance obj.
If lockMethod and unlockMethod are provided (not NULL), then these are called before and after calling method.
template<class C, typename T> ArServerDataProvider< C, T >::ArServerDataProvider (ArServerBase * server, const char * name, const char * description, C * obj, T(C::*)(void) const method, void(C::*)(void) lockMethod = NULL, void(C::*)(void) unlockMethod = NULL) inline
If this constructor is used, then access data by calling method on object instance obj.
If lockMethod and unlockMethod are provided (not NULL), then these are called before and after calling method. This version allows method to be const.
template<class C, typename T> virtual ArServerDataProvider< C, T >::~ArServerDataProvider () inline virtual
References ArFunctor::invoke(), ArLog::log(), ArServerBase::remData(), and ArLog::Verbose.
The documentation for this class was generated from the following file:
ArServerDataProvider.h