ArNetworking: ArServerAdvertiser Class Reference
ArServerAdvertiser Class Reference
Publish server information on local network for service discovery.
#include <ArServerAdvertiser.h>
Public Member Functions
ArServerAdvertiser (ArServerBase *server, const char *name, const char *description, const char *servertype=NULL)
void shutdown ()
virtual ~ArServerAdvertiser ()
Detailed Description
Publish server information on local network for service discovery.
On Linux, run the external /usr/bin/avahi-publish command to advertise this server using mDNS Service Discovery (mDNS-SD). The avahi-publish tool must be installed on the system (on Ubuntu, run sudo apt-get install avahi-utils to install). Use avahi-browse _arnetworking._tcp to search the mDNS system for ArNetworking services or install and run avahi-discover for a simple GUI listing of services.
On Windows, this class does nothing.
The external command is executed in a new process using vfork() when an instance of this object is instantiated. If this object is destroyed or shutdown() is called, or Aria::exit() is called, then the process is stopped (by sending it SIGKILL). Note: If you do not save the instance, the process will be killed immediately. Typical usage is to create an instance in main() after running the server with ArServerBase::runAsync().
Using this is optional and not neccesary to use ArNetworking, but it enables some convenience tools.
Note
Available on Linux only
Example:
...
server.runAsync();
ArServerAdvertiser adv(&server, "MyServer", "My special server");
...
Examples:
serverDemo.cpp.
Constructor & Destructor Documentation
ArServerAdvertiser::ArServerAdvertiser (ArServerBase * server, const char * name, const char * description, const char * servertype = NULL) inline
References Aria::addExitCallback(), ArServerBase::getTcpPort(), ArLog::log(), and ArLog::Verbose.
virtual ArServerAdvertiser::~ArServerAdvertiser () inline virtual
References shutdown().
Member Function Documentation
void ArServerAdvertiser::shutdown () inline
References ArLog::log(), ArLog::Normal, and ArLog::Verbose.
Referenced by ~ArServerAdvertiser().
The documentation for this class was generated from the following file:
ArServerAdvertiser.h