ArNetworking: ArClientDataReceiver< C, T > Class Template Reference
ArClientDataReceiver< C, T > Class Template Reference
A client program may use this to receive responses to data requests and pass the received data to a provided function or method, or save (cache) the most recently received data.
#include <ArClientDataReceiver.h>
Public Types
enum RequestType { Once, OnceUDP, Repeat, None }
Public Member Functions
ArClientDataReceiver (ArClientBase *client, const char *requestName, ArFunctor1< const T & > *functor, long interval)
Register a function to handle data of a specific type received from the server.
ArClientDataReceiver (ArClientBase *client, const char *requestName, C *obj, void(C::*function)(const T &), long interval=-1)
virtual ~ArClientDataReceiver ()
The destructor calls client->remHandler() to remove the handler, and client->requestStop() to stop receiving the data.
Detailed Description
template<class C, typename T>
class ArClientDataReceiver< C, T >
A client program may use this to receive responses to data requests and pass the received data to a provided function or method, or save (cache) the most recently received data.
See also
ArServerDataProvider
Note
If the server does not have the requested data item at time of request, it will not be requested. A warning will be logged.
Since
2.9.3
Member Enumeration Documentation
template<class C, typename T> enum ArClientDataReceiver::RequestType
Enumerator
Once
OnceUDP
Repeat
None
Constructor & Destructor Documentation
template<class C, typename T> ArClientDataReceiver< C, T >::ArClientDataReceiver (ArClientBase * client, const char * requestName, ArFunctor1< const T & > * functor, long interval) inline
Register a function to handle data of a specific type received from the server.
This class will call client->request(), client->requestOnce() or client->requestOnceUdp() to request the data after registering the handler.
Note
the data sent by the server must be of the given type, or
References ArClientBase::addHandler(), client, ArClientBase::dataExists(), ArLog::log(), ArLog::Normal, and ArClientBase::request().
template<class C, typename T> ArClientDataReceiver< C, T >::ArClientDataReceiver (ArClientBase * client, const char * requestName, C * obj, void(C::*)(const T &) function, long interval = -1) inline
template<class C, typename T> virtual ArClientDataReceiver< C, T >::~ArClientDataReceiver () inline virtual
The destructor calls client->remHandler() to remove the handler, and client->requestStop() to stop receiving the data.
References ArClientBase::remHandler().
The documentation for this class was generated from the following file:
ArClientDataReceiver.h