ArNetworking: ArServerModeTestLoop Class Reference
ArServerModeTestLoop Class Reference
This mode uses the most simple robot control commands to drive back and forth along a line repeatedly.
#include <ArServerModeTestLoop.h>
Public Member Functions
virtual void activate (void)
The function called when the mode is activated.
void addCommands (ArServerHandlerCommands *cmds)
void addToConfig (ArConfig *config)
ArServerModeTestLoop (ArServerBase *server, ArRobot *robot, ArConfig *config=NULL, ArServerHandlerCommands *cmds=NULL)
virtual void deactivate (void)
The function called when the mode is deactivated.
virtual ~ArServerModeTestLoop ()
Public Member Functions inherited from ArServerMode
virtual void activationDenied (void)
The function called if the mode is not activated because another mode superceded it.
void addActivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is activated.
void addAsDefaultMode (ArListPos::Pos pos=ArListPos::LAST)
Sets this mode to default (so if a mode deactivates it activates this)
void addDeactivateCallback (ArFunctor *functor, int position=50)
Adds a callback for when this class is deactivated.
bool addModeData (const char *name, const char *description, ArFunctor2< ArServerClient *, ArNetPacket * > *functor, const char *argumentDescription, const char *returnDescription, const char *commandGroup=NULL, const char *dataFlags=NULL)
This basically just notes the commands associated with a mode so that clients can know what can and can't happen based on what mode is active/locked/etc.
void addSingleShotDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for when this class is deactivated.
void addSingleShotPostDeactivateCallback (ArFunctor *functor, int position=50)
Adds a single shot callback for just after the deactivate happens (when the next mode has activated)
ArServerMode (ArRobot *robot, ArServerBase *server, const char *name)
Constructor.
virtual void forceUnlock (void)
This will be called if another mode has to break the lock.
virtual ArActionGroup * getActionGroup (void)
This function should return the action group this mode uses.
ArTime getActivityTime (void)
Gets the time of our last activity.
const char * getExtendedStatus (void) const
Gets a string representing the extended status of the mode we're in.
const char * getMode (void) const
Gets a string representing the mode we're in.
const char * getName (void) const
Gets the name of the mode we're in.
const char * getStatus (void) const
Gets a string representing the status of the mode we're in.
bool hasSetActivityTime (void)
Gets if we've set our activity time.
void internalSetActivityTime (ArTime time)
Internal call to set the activity time (this is dangerous and shouldn't be used)
bool isActive (void) const
Gets if this mode is active or not.
virtual bool isAutoResumeAfterInterrupt ()
Adds data to the list of this mode's commands.
void lockMode (bool willUnlockIfRequested=false)
Locks this mode in until its unlocked (mode must be the active mode)
void remActivateCallback (ArFunctor *functor)
Removes a callback for when this class is activated.
void remDeactivateCallback (ArFunctor *functor)
Removes a callback for when this class is deactivated.
void remSingleShotDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for when this class is deactivated.
void remSingleShotPostDeactivateCallback (ArFunctor *functor)
Removes a single shot callback for just after the deactivate happens (when the next mode has activated)
virtual void requestUnlock (void)
This will be called if another mode wants the lock broken (can ignore)
void setActivityTimeToNow (void)
Sets that we're active right now.
void setMode (const char *str)
This should only be used by careful people and probably not then.
void setStatus (const char *str)
This should only be used by careful people and probably not then.
void unlockMode (void)
Unlocks the mode so other modes can activate.
virtual ~ArServerMode ()
Destructor.
Protected Types
enum { Trans, Stop, Rot, Deactivated }
Protected Attributes
ArFunctorC< ArServerModeTestLoop > myActivateCB
int myDriveDist
ArFunctor2C< ArServerModeTestLoop, ArServerClient *, ArNetPacket * > myNetTestLoopCB
int myObsDecel
int myPadding
int myRotAccel
int myRotDecel
int myRotSpeed
int mySpeed
ArPose myStartPos
enum ArServerModeTestLoop:: { ... } myState
int myStopDist
Protected Attributes inherited from ArServerMode
ArCallbackList myActivateCallbacks
ArTime myActivityTime
ArMutex myActivityTimeMutex
ArCallbackList myDeactivateCallbacks
std::string myExtendedStatus
bool myHasSetActivityTime
bool myIsActive
std::string myMode
std::string myName
ArRobot * myRobot
ArServerBase * myServer
bool mySetActivityThisCycle
ArCallbackList mySingleShotDeactivateCallbacks
ArCallbackList mySingleShotPostDeactivateCallbacks
std::string myStatus
bool myStatusSetThisCycle
ArLog::LogLevel myVerboseLogLevel
Additional Inherited Members
Static Public Member Functions inherited from ArServerMode
static ArServerMode * getActiveMode (void)
Gets the active mode.
static int getActiveModeActivityTimeSecSince (void)
Gets the seconds since the activity of our active mode.
static const char * getActiveModeExtendedStatusString (void)
Gets the active extended status string.
static const char * getActiveModeModeString (void)
Gets the active mode string.
static bool getActiveModeSetActivityThisCycle (void)
Gets if the active mode set the activity time this cycle or not.
static const char * getActiveModeStatusString (void)
Gets the active status string.
static ArServerModeIdle * getIdleMode (void)
Call that gets our idle mode.
static void getModeBusy (ArServerClient *client, ArNetPacket *packet)
Handles the packet request for the mode busy state.
static void getModeDataList (ArServerClient *client, ArNetPacket *packet)
Gets the list of data for each mode.
static void getModeInfo (ArServerClient *client, ArNetPacket *packet)
Gets the info about which mode is active and such.
static bool isLocked (void)
Gets if the active mode is locked or not.
static bool willUnlockIfRequested (void)
Gets whether we'll unlock if requested or not.
Protected Member Functions inherited from ArServerMode
bool baseActivate (bool canSelfActivateIfLocked=false)
Activates this mode if it can (returns true if it can, false otherwise).
void baseDeactivate (void)
Deactivates this mode.
void checkBroadcastModeInfoPacket (void)
ArServerMode * getLastActiveMode ()
Static Protected Member Functions inherited from ArServerMode
static void buildModeInfoPacket (ArNetPacket *packet)
static std::list< ArServerMode * > * getRequestedActivateModes (void)
static void modeUserTask (void)
Static Protected Attributes inherited from ArServerMode
static ArServerMode * ourActiveMode = NULL
static bool ourActiveModeLocked = false
static bool ourActiveModeSetActivityThisCycle = false
static bool ourActiveModeWillUnlockIfRequested = false
static ArServerMode * ourBroadcastActiveMode = NULL
static bool ourBroadcastActiveModeLocked = false
static bool ourBroadcastActiveModeWillUnlockIfRequested = false
static std::list< ArServerMode * > ourDefaultModes
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeBusyCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeDataListCB
static ArGlobalFunctor2< ArServerClient *, ArNetPacket * > ourGetModeInfoCB
static ArServerModeIdle * ourIdleMode = NULL
static bool ourIdleModeCreated = false
static ArMutex ourIdleModeMutex
static bool ourIsBusy = false
static ArServerMode * ourLastActiveMode = NULL
static std::multimap< std::string, std::string > ourModeDataMap
static ArMutex ourModeDataMapMutex
static std::list< ArServerMode * > ourModes
static ArServerMode * ourNextActiveMode = NULL
static std::list< ArServerMode * > ourRequestedActivateModes
static ArServerBase * ourServerBase = NULL
static bool ourUserTaskAdded = false
static ArGlobalFunctor ourUserTaskCB
Detailed Description
This mode uses the most simple robot control commands to drive back and forth along a line repeatedly.
It can be activated by an ArNetworking "testloop" request, or by a user using custom text commands interface (if command handler is passed in constructor or addCommands() is called). Some options are added to the configuration if addToConfig() is called or an ArConfig object is given in the constructor.
Examples:
serverDemo.cpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
Trans
Stop
Rot
Deactivated
Constructor & Destructor Documentation
ArServerModeTestLoop::ArServerModeTestLoop (ArServerBase * server, ArRobot * robot, ArConfig * config = NULL, ArServerHandlerCommands * cmds = NULL)
References addCommands(), ArServerMode::addModeData(), addToConfig(), ArServerMode::myMode, myNetTestLoopCB, and ArServerMode::myServer.
ArServerModeTestLoop::~ArServerModeTestLoop () virtual
Member Function Documentation
void ArServerModeTestLoop::activate (void) virtual
The function called when the mode is activated.
Subclasses must implement this, but also call baseActivate().-
Implements ArServerMode.
References ArServerMode::baseActivate(), ArRobot::clearDirectMotion(), ArRobot::getPose(), ArServerMode::myRobot, myStartPos, myState, ArServerMode::myStatus, ArServerMode::setActivityTimeToNow(), and Trans.
Referenced by deactivate().
void ArServerModeTestLoop::addCommands (ArServerHandlerCommands * cmds)
References ArServerHandlerCommands::addCommand(), and myActivateCB.
Referenced by ArServerModeTestLoop().
void ArServerModeTestLoop::addToConfig (ArConfig * config)
References ArConfig::addParam(), myDriveDist, myObsDecel, myPadding, myRotAccel, myRotSpeed, mySpeed, and myStopDist.
Referenced by ArServerModeTestLoop().
void ArServerModeTestLoop::deactivate (void) virtual
The function called when the mode is deactivated.
Subclasses must implement this, and also call baseDeactivate().
Implements ArServerMode.
References activate(), ArServerMode::baseDeactivate(), ArRobot::checkRangeDevicesCurrentBox(), client, Deactivated, ArPose::findDistanceTo(), ArRobot::getPose(), ArRobot::getRangeDeviceList(), ArRobot::getRobotLength(), ArRobot::getRobotWidth(), ArServerMode::isActive(), ArRobot::isHeadingDone(), ArRobot::isStopped(), ArRobot::lock(), ArLog::log(), myDriveDist, myObsDecel, myPadding, ArServerMode::myRobot, myRotAccel, myRotDecel, myRotSpeed, mySpeed, myStartPos, myState, ArServerMode::myStatus, myStopDist, Rot, ArServerMode::setActivityTimeToNow(), ArRobot::setDeltaHeading(), ArRobot::setRotAccel(), ArRobot::setRotDecel(), ArRobot::setRotVelMax(), ArRobot::setTransDecel(), ArRobot::setVel(), ArRobot::stop(), Stop, ArLog::Terse, Trans, ArRobot::unlock(), and ArLog::Verbose.
Member Data Documentation
ArFunctorC<ArServerModeTestLoop> ArServerModeTestLoop::myActivateCB protected
Referenced by addCommands().
int ArServerModeTestLoop::myDriveDist protected
Referenced by addToConfig(), and deactivate().
ArFunctor2C<ArServerModeTestLoop, ArServerClient *, ArNetPacket *> ArServerModeTestLoop::myNetTestLoopCB protected
Referenced by ArServerModeTestLoop().
int ArServerModeTestLoop::myObsDecel protected
Referenced by addToConfig(), and deactivate().
int ArServerModeTestLoop::myPadding protected
Referenced by addToConfig(), and deactivate().
int ArServerModeTestLoop::myRotAccel protected
Referenced by addToConfig(), and deactivate().
int ArServerModeTestLoop::myRotDecel protected
Referenced by deactivate().
int ArServerModeTestLoop::myRotSpeed protected
Referenced by addToConfig(), and deactivate().
int ArServerModeTestLoop::mySpeed protected
Referenced by addToConfig(), and deactivate().
ArPose ArServerModeTestLoop::myStartPos protected
Referenced by activate(), and deactivate().
enum { ... } ArServerModeTestLoop::myState
Referenced by activate(), and deactivate().
int ArServerModeTestLoop::myStopDist protected
Referenced by addToConfig(), and deactivate().
The documentation for this class was generated from the following files:
ArServerModeTestLoop.h
ArServerModeTestLoop.cpp