ArNetworking: ArServerModeWander::StopIfNoRangeDevicesAction Class Reference
ArServerModeWander::StopIfNoRangeDevicesAction Class Reference
#include <ArServerModeWander.h>
Public Member Functions
StopIfNoRangeDevicesAction ()
Public Member Functions inherited from ArAction
virtual void activate (void)
ArAction (const char *name, const char *description="")
virtual void deactivate (void)
virtual const ArArg * getArg (int number) const
virtual ArArg * getArg (int number)
virtual const char * getDescription (void) const
virtual ArActionDesired * getDesired (void)
virtual const ArActionDesired * getDesired (void) const
virtual const char * getName (void) const
virtual int getNumArgs (void) const
ArRobot * getRobot () const
virtual bool isActive (void) const
virtual void log (bool verbose=true) const
virtual void setRobot (ArRobot *robot)
virtual ~ArAction ()
Additional Inherited Members
Static Public Member Functions inherited from ArAction
static bool getDefaultActivationState (void)
static void setDefaultActivationState (bool defaultActivationState)
Protected Member Functions inherited from ArAction
void setNextArgument (ArArg const &arg)
Protected Attributes inherited from ArAction
ArRobot * myRobot
Constructor & Destructor Documentation
ArServerModeWander::StopIfNoRangeDevicesAction::StopIfNoRangeDevicesAction () inline
References ArAction::getRobot(), ArActionDesired::reset(), ArActionDesired::setMaxLeftLatVel(), ArActionDesired::setMaxNegVel(), ArActionDesired::setMaxRightLatVel(), ArActionDesired::setMaxRotVel(), and ArActionDesired::setMaxVel().
The documentation for this class was generated from the following file:
ArServerModeWander.h