/*
Adept MobileRobots Robotics Interface for Applications (ARIA)
Copyright (C) 2004-2005 ActivMedia Robotics LLC
Copyright (C) 2006-2010 MobileRobots Inc.
Copyright (C) 2011-2015 Adept Technology, Inc.
Copyright (C) 2016-2018 Omron Adept Technologies, Inc.

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
Adept MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
Adept MobileRobots, 10 Columbia Drive, Amherst, NH 03031; +1-603-881-7960
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArGenericCallbackList_ArFunctorP {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ArGenericCallbackList_ArFunctorP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ArGenericCallbackList_ArFunctorP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArGenericCallbackList_ArFunctorP(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArGenericCallbackList_ArFunctorP(String name, ArLog.LogLevel logLevel, boolean singleShot) {
    this(AriaJavaJNI.new_ArGenericCallbackList_ArFunctorP__SWIG_0(name, logLevel.swigValue(), singleShot), true);
  }

  public ArGenericCallbackList_ArFunctorP(String name, ArLog.LogLevel logLevel) {
    this(AriaJavaJNI.new_ArGenericCallbackList_ArFunctorP__SWIG_1(name, logLevel.swigValue()), true);
  }

  public ArGenericCallbackList_ArFunctorP(String name) {
    this(AriaJavaJNI.new_ArGenericCallbackList_ArFunctorP__SWIG_2(name), true);
  }

  public ArGenericCallbackList_ArFunctorP() {
    this(AriaJavaJNI.new_ArGenericCallbackList_ArFunctorP__SWIG_3(), true);
  }

  public void addCallback(ArFunctor functor, int position) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_addCallback__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position);
  }

  public void addCallback(ArFunctor functor) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_addCallback__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remCallback(ArFunctor functor) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_remCallback(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void setName(String name) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_setName(swigCPtr, this, name);
  }

  public void setLogLevel(ArLog.LogLevel logLevel) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_setLogLevel(swigCPtr, this, logLevel.swigValue());
  }

  public void setSingleShot(boolean singleShot) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_setSingleShot(swigCPtr, this, singleShot);
  }

  public void setLogging(boolean on) {
    AriaJavaJNI.ArGenericCallbackList_ArFunctorP_setLogging(swigCPtr, this, on);
  }

}
