/*
Adept MobileRobots Robotics Interface for Applications (ARIA)
Copyright (C) 2004-2005 ActivMedia Robotics LLC
Copyright (C) 2006-2010 MobileRobots Inc.
Copyright (C) 2011-2015 Adept Technology, Inc.
Copyright (C) 2016-2018 Omron Adept Technologies, Inc.

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
Adept MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
Adept MobileRobots, 10 Columbia Drive, Amherst, NH 03031; +1-603-881-7960
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMap extends ArMapInterface {
  private transient long swigCPtr;

  public ArMap(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.ArMap_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ArMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMap(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AriaJavaJNI.ArMap_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AriaJavaJNI.ArMap_change_ownership(this, swigCPtr, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam, String configDesc, boolean ignoreEmptyFileName, ArPriority.Priority priority, String tempDirectory, int configProcessFilePriority) {
    this(AriaJavaJNI.new_ArMap__SWIG_0(baseDirectory, addToGlobalConfig, configSection, configParam, configDesc, ignoreEmptyFileName, priority.swigValue(), tempDirectory, configProcessFilePriority), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam, String configDesc, boolean ignoreEmptyFileName, ArPriority.Priority priority, String tempDirectory) {
    this(AriaJavaJNI.new_ArMap__SWIG_1(baseDirectory, addToGlobalConfig, configSection, configParam, configDesc, ignoreEmptyFileName, priority.swigValue(), tempDirectory), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam, String configDesc, boolean ignoreEmptyFileName, ArPriority.Priority priority) {
    this(AriaJavaJNI.new_ArMap__SWIG_2(baseDirectory, addToGlobalConfig, configSection, configParam, configDesc, ignoreEmptyFileName, priority.swigValue()), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam, String configDesc, boolean ignoreEmptyFileName) {
    this(AriaJavaJNI.new_ArMap__SWIG_3(baseDirectory, addToGlobalConfig, configSection, configParam, configDesc, ignoreEmptyFileName), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam, String configDesc) {
    this(AriaJavaJNI.new_ArMap__SWIG_4(baseDirectory, addToGlobalConfig, configSection, configParam, configDesc), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection, String configParam) {
    this(AriaJavaJNI.new_ArMap__SWIG_5(baseDirectory, addToGlobalConfig, configSection, configParam), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig, String configSection) {
    this(AriaJavaJNI.new_ArMap__SWIG_6(baseDirectory, addToGlobalConfig, configSection), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory, boolean addToGlobalConfig) {
    this(AriaJavaJNI.new_ArMap__SWIG_7(baseDirectory, addToGlobalConfig), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(String baseDirectory) {
    this(AriaJavaJNI.new_ArMap__SWIG_8(baseDirectory), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap() {
    this(AriaJavaJNI.new_ArMap__SWIG_9(), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public ArMap(ArMap other) {
    this(AriaJavaJNI.new_ArMap__SWIG_10(ArMap.getCPtr(other), other), true);
    AriaJavaJNI.ArMap_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public SWIGTYPE_p_std__listT_std__string_t getScanTypes() {
    return new SWIGTYPE_p_std__listT_std__string_t((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getScanTypes(swigCPtr, this) : AriaJavaJNI.ArMap_getScanTypesSwigExplicitArMap(swigCPtr, this), true);
  }

  public boolean setScanTypes(SWIGTYPE_p_std__listT_std__string_t scanTypeList) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setScanTypes(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(scanTypeList)) : AriaJavaJNI.ArMap_setScanTypesSwigExplicitArMap(swigCPtr, this, SWIGTYPE_p_std__listT_std__string_t.getCPtr(scanTypeList));
  }

  public int lock() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_lock(swigCPtr, this) : AriaJavaJNI.ArMap_lockSwigExplicitArMap(swigCPtr, this);
  }

  public int tryLock() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_tryLock(swigCPtr, this) : AriaJavaJNI.ArMap_tryLockSwigExplicitArMap(swigCPtr, this);
  }

  public int unlock() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_unlock(swigCPtr, this) : AriaJavaJNI.ArMap_unlockSwigExplicitArMap(swigCPtr, this);
  }

  public String getDisplayString(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getDisplayString__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getDisplayStringSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public String getDisplayString() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getDisplayString__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getDisplayStringSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public ArPoseVector getPoints(String scanType) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getPoints__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getPointsSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
    return (cPtr == 0) ? null : new ArPoseVector(cPtr, false);
  }

  public ArPoseVector getPoints() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getPoints__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getPointsSwigExplicitArMap__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ArPoseVector(cPtr, false);
  }

  public ArPose getMinPose(String scanType) {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMinPose__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getMinPoseSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType), true);
  }

  public ArPose getMinPose() {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMinPose__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getMinPoseSwigExplicitArMap__SWIG_1(swigCPtr, this), true);
  }

  public ArPose getMaxPose(String scanType) {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMaxPose__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getMaxPoseSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType), true);
  }

  public ArPose getMaxPose() {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMaxPose__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getMaxPoseSwigExplicitArMap__SWIG_1(swigCPtr, this), true);
  }

  public int getNumPoints(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getNumPoints__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getNumPointsSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public int getNumPoints() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getNumPoints__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getNumPointsSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public boolean isSortedPoints(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isSortedPoints__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_isSortedPointsSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public boolean isSortedPoints() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isSortedPoints__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_isSortedPointsSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public void setPoints(ArPoseVector points, String scanType, boolean isSortedPoints, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setPoints__SWIG_0(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType, isSortedPoints, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)); else AriaJavaJNI.ArMap_setPointsSwigExplicitArMap__SWIG_0(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType, isSortedPoints, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setPoints(ArPoseVector points, String scanType, boolean isSortedPoints) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setPoints__SWIG_1(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType, isSortedPoints); else AriaJavaJNI.ArMap_setPointsSwigExplicitArMap__SWIG_1(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType, isSortedPoints);
  }

  public void setPoints(ArPoseVector points, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setPoints__SWIG_2(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType); else AriaJavaJNI.ArMap_setPointsSwigExplicitArMap__SWIG_2(swigCPtr, this, ArPoseVector.getCPtr(points), points, scanType);
  }

  public void setPoints(ArPoseVector points) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setPoints__SWIG_3(swigCPtr, this, ArPoseVector.getCPtr(points), points); else AriaJavaJNI.ArMap_setPointsSwigExplicitArMap__SWIG_3(swigCPtr, this, ArPoseVector.getCPtr(points), points);
  }

  public ArLineSegmentVector getLines(String scanType) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLines__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getLinesSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
    return (cPtr == 0) ? null : new ArLineSegmentVector(cPtr, false);
  }

  public ArLineSegmentVector getLines() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLines__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getLinesSwigExplicitArMap__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ArLineSegmentVector(cPtr, false);
  }

  public ArPose getLineMinPose(String scanType) {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLineMinPose__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getLineMinPoseSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType), true);
  }

  public ArPose getLineMinPose() {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLineMinPose__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getLineMinPoseSwigExplicitArMap__SWIG_1(swigCPtr, this), true);
  }

  public ArPose getLineMaxPose(String scanType) {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLineMaxPose__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getLineMaxPoseSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType), true);
  }

  public ArPose getLineMaxPose() {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getLineMaxPose__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getLineMaxPoseSwigExplicitArMap__SWIG_1(swigCPtr, this), true);
  }

  public int getNumLines(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getNumLines__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getNumLinesSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public int getNumLines() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getNumLines__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getNumLinesSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public boolean isSortedLines(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isSortedLines__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_isSortedLinesSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public boolean isSortedLines() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isSortedLines__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_isSortedLinesSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public void setLines(ArLineSegmentVector lines, String scanType, boolean isSortedLines, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setLines__SWIG_0(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType, isSortedLines, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)); else AriaJavaJNI.ArMap_setLinesSwigExplicitArMap__SWIG_0(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType, isSortedLines, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setLines(ArLineSegmentVector lines, String scanType, boolean isSortedLines) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setLines__SWIG_1(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType, isSortedLines); else AriaJavaJNI.ArMap_setLinesSwigExplicitArMap__SWIG_1(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType, isSortedLines);
  }

  public void setLines(ArLineSegmentVector lines, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setLines__SWIG_2(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType); else AriaJavaJNI.ArMap_setLinesSwigExplicitArMap__SWIG_2(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines, scanType);
  }

  public void setLines(ArLineSegmentVector lines) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setLines__SWIG_3(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines); else AriaJavaJNI.ArMap_setLinesSwigExplicitArMap__SWIG_3(swigCPtr, this, ArLineSegmentVector.getCPtr(lines), lines);
  }

  public int getResolution(String scanType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getResolution__SWIG_0(swigCPtr, this, scanType) : AriaJavaJNI.ArMap_getResolutionSwigExplicitArMap__SWIG_0(swigCPtr, this, scanType);
  }

  public int getResolution() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getResolution__SWIG_1(swigCPtr, this) : AriaJavaJNI.ArMap_getResolutionSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public void setResolution(int resolution, String scanType, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setResolution__SWIG_0(swigCPtr, this, resolution, scanType, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)); else AriaJavaJNI.ArMap_setResolutionSwigExplicitArMap__SWIG_0(swigCPtr, this, resolution, scanType, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setResolution(int resolution, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setResolution__SWIG_1(swigCPtr, this, resolution, scanType); else AriaJavaJNI.ArMap_setResolutionSwigExplicitArMap__SWIG_1(swigCPtr, this, resolution, scanType);
  }

  public void setResolution(int resolution) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setResolution__SWIG_2(swigCPtr, this, resolution); else AriaJavaJNI.ArMap_setResolutionSwigExplicitArMap__SWIG_2(swigCPtr, this, resolution);
  }

  public void writeScanToFunctor(ArFunctor1_CString functor, String endOfLineChars, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeScanToFunctor__SWIG_0(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, scanType); else AriaJavaJNI.ArMap_writeScanToFunctorSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, scanType);
  }

  public void writeScanToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeScanToFunctor__SWIG_1(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeScanToFunctorSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void writePointsToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t functor, String scanType, ArFunctor1_CString keywordFunctor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writePointsToFunctor__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor), scanType, ArFunctor1_CString.getCPtr(keywordFunctor), keywordFunctor); else AriaJavaJNI.ArMap_writePointsToFunctorSwigExplicitArMap__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor), scanType, ArFunctor1_CString.getCPtr(keywordFunctor), keywordFunctor);
  }

  public void writePointsToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t functor, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writePointsToFunctor__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor), scanType); else AriaJavaJNI.ArMap_writePointsToFunctorSwigExplicitArMap__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor), scanType);
  }

  public void writePointsToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writePointsToFunctor__SWIG_2(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor)); else AriaJavaJNI.ArMap_writePointsToFunctorSwigExplicitArMap__SWIG_2(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArPose_t_p_t.getCPtr(functor));
  }

  public void writeLinesToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t functor, String scanType, ArFunctor1_CString keywordFunctor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeLinesToFunctor__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor), scanType, ArFunctor1_CString.getCPtr(keywordFunctor), keywordFunctor); else AriaJavaJNI.ArMap_writeLinesToFunctorSwigExplicitArMap__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor), scanType, ArFunctor1_CString.getCPtr(keywordFunctor), keywordFunctor);
  }

  public void writeLinesToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t functor, String scanType) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeLinesToFunctor__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor), scanType); else AriaJavaJNI.ArMap_writeLinesToFunctorSwigExplicitArMap__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor), scanType);
  }

  public void writeLinesToFunctor(SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeLinesToFunctor__SWIG_2(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor)); else AriaJavaJNI.ArMap_writeLinesToFunctorSwigExplicitArMap__SWIG_2(swigCPtr, this, SWIGTYPE_p_ArFunctor2T_int_std__vectorT_ArLineSegment_t_p_t.getCPtr(functor));
  }

  public boolean addToFileParser(ArFileParser fileParser) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_addToFileParser(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser) : AriaJavaJNI.ArMap_addToFileParserSwigExplicitArMap(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser);
  }

  public boolean remFromFileParser(ArFileParser fileParser) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_remFromFileParser(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser) : AriaJavaJNI.ArMap_remFromFileParserSwigExplicitArMap(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser);
  }

  public boolean readDataPoint(String line) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_readDataPoint(swigCPtr, this, line) : AriaJavaJNI.ArMap_readDataPointSwigExplicitArMap(swigCPtr, this, line);
  }

  public boolean readLineSegment(String line) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_readLineSegment(swigCPtr, this, line) : AriaJavaJNI.ArMap_readLineSegmentSwigExplicitArMap(swigCPtr, this, line);
  }

  public void loadDataPoint(double x, double y) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_loadDataPoint(swigCPtr, this, x, y); else AriaJavaJNI.ArMap_loadDataPointSwigExplicitArMap(swigCPtr, this, x, y);
  }

  public void loadLineSegment(double x1, double y1, double x2, double y2) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_loadLineSegment(swigCPtr, this, x1, y1, x2, y2); else AriaJavaJNI.ArMap_loadLineSegmentSwigExplicitArMap(swigCPtr, this, x1, y1, x2, y2);
  }

  public ArMapObject findFirstMapObject(String name, String type, boolean isIncludeWithHeading) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findFirstMapObject__SWIG_0(swigCPtr, this, name, type, isIncludeWithHeading) : AriaJavaJNI.ArMap_findFirstMapObjectSwigExplicitArMap__SWIG_0(swigCPtr, this, name, type, isIncludeWithHeading);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

  public ArMapObject findFirstMapObject(String name, String type) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findFirstMapObject__SWIG_1(swigCPtr, this, name, type) : AriaJavaJNI.ArMap_findFirstMapObjectSwigExplicitArMap__SWIG_1(swigCPtr, this, name, type);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

  public ArMapObject findMapObject(String name, String type, boolean isIncludeWithHeading) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObject__SWIG_0(swigCPtr, this, name, type, isIncludeWithHeading) : AriaJavaJNI.ArMap_findMapObjectSwigExplicitArMap__SWIG_0(swigCPtr, this, name, type, isIncludeWithHeading);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

  public ArMapObject findMapObject(String name, String type) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObject__SWIG_1(swigCPtr, this, name, type) : AriaJavaJNI.ArMap_findMapObjectSwigExplicitArMap__SWIG_1(swigCPtr, this, name, type);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

  public ArMapObject findMapObject(String name) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObject__SWIG_2(swigCPtr, this, name) : AriaJavaJNI.ArMap_findMapObjectSwigExplicitArMap__SWIG_2(swigCPtr, this, name);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

  public ArMapObjectPtrList findMapObjectsOfType(String type, boolean isIncludeWithHeading) {
    return new ArMapObjectPtrList((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObjectsOfType__SWIG_0(swigCPtr, this, type, isIncludeWithHeading) : AriaJavaJNI.ArMap_findMapObjectsOfTypeSwigExplicitArMap__SWIG_0(swigCPtr, this, type, isIncludeWithHeading), true);
  }

  public ArMapObjectPtrList findMapObjectsOfType(String type) {
    return new ArMapObjectPtrList((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObjectsOfType__SWIG_1(swigCPtr, this, type) : AriaJavaJNI.ArMap_findMapObjectsOfTypeSwigExplicitArMap__SWIG_1(swigCPtr, this, type), true);
  }

  public ArMapObjectPtrList getMapObjects() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapObjects(swigCPtr, this) : AriaJavaJNI.ArMap_getMapObjectsSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArMapObjectPtrList(cPtr, false);
  }

  public void setMapObjects(ArMapObjectPtrList mapObjects, boolean isSortedObjects, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setMapObjects__SWIG_0(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects, isSortedObjects, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)); else AriaJavaJNI.ArMap_setMapObjectsSwigExplicitArMap__SWIG_0(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects, isSortedObjects, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setMapObjects(ArMapObjectPtrList mapObjects, boolean isSortedObjects) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setMapObjects__SWIG_1(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects, isSortedObjects); else AriaJavaJNI.ArMap_setMapObjectsSwigExplicitArMap__SWIG_1(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects, isSortedObjects);
  }

  public void setMapObjects(ArMapObjectPtrList mapObjects) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setMapObjects__SWIG_2(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects); else AriaJavaJNI.ArMap_setMapObjectsSwigExplicitArMap__SWIG_2(swigCPtr, this, ArMapObjectPtrList.getCPtr(mapObjects), mapObjects);
  }

  public void writeObjectListToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeObjectListToFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeObjectListToFunctorSwigExplicitArMap(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void offsetMapContents(ArPose offset) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_offsetMapContents(swigCPtr, this, ArPose.getCPtr(offset), offset); else AriaJavaJNI.ArMap_offsetMapContentsSwigExplicitArMap(swigCPtr, this, ArPose.getCPtr(offset), offset);
  }

  public ArArgumentBuilderPtrList getInfo(String infoName) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInfo__SWIG_0(swigCPtr, this, infoName) : AriaJavaJNI.ArMap_getInfoSwigExplicitArMap__SWIG_0(swigCPtr, this, infoName);
    return (cPtr == 0) ? null : new ArArgumentBuilderPtrList(cPtr, false);
  }

  public ArArgumentBuilderPtrList getInfo(int infoType) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInfo__SWIG_1(swigCPtr, this, infoType) : AriaJavaJNI.ArMap_getInfoSwigExplicitArMap__SWIG_1(swigCPtr, this, infoType);
    return (cPtr == 0) ? null : new ArArgumentBuilderPtrList(cPtr, false);
  }

  public ArArgumentBuilderPtrList getMapInfo() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapInfo(swigCPtr, this) : AriaJavaJNI.ArMap_getMapInfoSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArArgumentBuilderPtrList(cPtr, false);
  }

  public int getInfoCount() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInfoCount(swigCPtr, this) : AriaJavaJNI.ArMap_getInfoCountSwigExplicitArMap(swigCPtr, this);
  }

  public SWIGTYPE_p_std__listT_std__string_t getInfoNames() {
    return new SWIGTYPE_p_std__listT_std__string_t((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInfoNames(swigCPtr, this) : AriaJavaJNI.ArMap_getInfoNamesSwigExplicitArMap(swigCPtr, this), true);
  }

  public boolean setInfo(String infoName, ArArgumentBuilderPtrList infoList, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setInfo__SWIG_0(swigCPtr, this, infoName, ArArgumentBuilderPtrList.getCPtr(infoList), infoList, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)) : AriaJavaJNI.ArMap_setInfoSwigExplicitArMap__SWIG_0(swigCPtr, this, infoName, ArArgumentBuilderPtrList.getCPtr(infoList), infoList, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public boolean setInfo(String infoName, ArArgumentBuilderPtrList infoList) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setInfo__SWIG_1(swigCPtr, this, infoName, ArArgumentBuilderPtrList.getCPtr(infoList), infoList) : AriaJavaJNI.ArMap_setInfoSwigExplicitArMap__SWIG_1(swigCPtr, this, infoName, ArArgumentBuilderPtrList.getCPtr(infoList), infoList);
  }

  public boolean setInfo(int infoType, ArArgumentBuilderPtrList infoList, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setInfo__SWIG_2(swigCPtr, this, infoType, ArArgumentBuilderPtrList.getCPtr(infoList), infoList, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)) : AriaJavaJNI.ArMap_setInfoSwigExplicitArMap__SWIG_2(swigCPtr, this, infoType, ArArgumentBuilderPtrList.getCPtr(infoList), infoList, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public boolean setInfo(int infoType, ArArgumentBuilderPtrList infoList) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setInfo__SWIG_3(swigCPtr, this, infoType, ArArgumentBuilderPtrList.getCPtr(infoList), infoList) : AriaJavaJNI.ArMap_setInfoSwigExplicitArMap__SWIG_3(swigCPtr, this, infoType, ArArgumentBuilderPtrList.getCPtr(infoList), infoList);
  }

  public boolean setMapInfo(ArArgumentBuilderPtrList mapInfo, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setMapInfo__SWIG_0(swigCPtr, this, ArArgumentBuilderPtrList.getCPtr(mapInfo), mapInfo, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)) : AriaJavaJNI.ArMap_setMapInfoSwigExplicitArMap__SWIG_0(swigCPtr, this, ArArgumentBuilderPtrList.getCPtr(mapInfo), mapInfo, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public boolean setMapInfo(ArArgumentBuilderPtrList mapInfo) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setMapInfo__SWIG_1(swigCPtr, this, ArArgumentBuilderPtrList.getCPtr(mapInfo), mapInfo) : AriaJavaJNI.ArMap_setMapInfoSwigExplicitArMap__SWIG_1(swigCPtr, this, ArArgumentBuilderPtrList.getCPtr(mapInfo), mapInfo);
  }

  public String getInfoName(int infoType) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInfoName(swigCPtr, this, infoType) : AriaJavaJNI.ArMap_getInfoNameSwigExplicitArMap(swigCPtr, this, infoType);
  }

  public void writeInfoToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeInfoToFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeInfoToFunctorSwigExplicitArMap(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public boolean hasOriginLatLongAlt() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_hasOriginLatLongAlt(swigCPtr, this) : AriaJavaJNI.ArMap_hasOriginLatLongAltSwigExplicitArMap(swigCPtr, this);
  }

  public boolean hasOriginLatLonAlt() {
    return AriaJavaJNI.ArMap_hasOriginLatLonAlt(swigCPtr, this);
  }

  public ArPose getOriginLatLong() {
    return new ArPose((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getOriginLatLong(swigCPtr, this) : AriaJavaJNI.ArMap_getOriginLatLongSwigExplicitArMap(swigCPtr, this), true);
  }

  public ArPose getOriginLatLon() {
    return new ArPose(AriaJavaJNI.ArMap_getOriginLatLon(swigCPtr, this), true);
  }

  public double getOriginAltitude() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getOriginAltitude(swigCPtr, this) : AriaJavaJNI.ArMap_getOriginAltitudeSwigExplicitArMap(swigCPtr, this);
  }

  public double getOriginLatitude() {
    return AriaJavaJNI.ArMap_getOriginLatitude(swigCPtr, this);
  }

  public double getOriginLongitude() {
    return AriaJavaJNI.ArMap_getOriginLongitude(swigCPtr, this);
  }

  public ArLLACoords getOriginLLA() {
    return new ArLLACoords(AriaJavaJNI.ArMap_getOriginLLA(swigCPtr, this), true);
  }

  public void setOriginLatLongAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setOriginLatLongAlt__SWIG_0(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)); else AriaJavaJNI.ArMap_setOriginLatLongAltSwigExplicitArMap__SWIG_0(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setOriginLatLongAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setOriginLatLongAlt__SWIG_1(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude); else AriaJavaJNI.ArMap_setOriginLatLongAltSwigExplicitArMap__SWIG_1(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude);
  }

  public void setOriginLatLonAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    AriaJavaJNI.ArMap_setOriginLatLonAlt__SWIG_0(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setOriginLatLonAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude) {
    AriaJavaJNI.ArMap_setOriginLatLonAlt__SWIG_1(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude);
  }

  public void writeSupplementToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeSupplementToFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeSupplementToFunctorSwigExplicitArMap(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void clear() {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_clear(swigCPtr, this); else AriaJavaJNI.ArMap_clearSwigExplicitArMap(swigCPtr, this);
  }

  public boolean set(ArMapInterface other) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_set(swigCPtr, this, ArMapInterface.getCPtr(other), other) : AriaJavaJNI.ArMap_setSwigExplicitArMap(swigCPtr, this, ArMapInterface.getCPtr(other), other);
  }

  public ArMapInterface cloneMap() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_cloneMap(swigCPtr, this) : AriaJavaJNI.ArMap_cloneMapSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArMapInterface(cPtr, false);
  }

  public void mapChanged() {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_mapChanged__SWIG_0(swigCPtr, this); else AriaJavaJNI.ArMap_mapChangedSwigExplicitArMap__SWIG_0(swigCPtr, this);
  }

  public void mapChanged(boolean invokePathPlanningCB, boolean invokeLocalizationCB) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_mapChanged__SWIG_1(swigCPtr, this, invokePathPlanningCB, invokeLocalizationCB); else AriaJavaJNI.ArMap_mapChangedSwigExplicitArMap__SWIG_1(swigCPtr, this, invokePathPlanningCB, invokeLocalizationCB);
  }

  public void addMapChangedCB(ArFunctor functor, int position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position); else AriaJavaJNI.ArMap_addMapChangedCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position);
  }

  public void addMapChangedCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addMapChangedCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remMapChangedCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remMapChangedCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remMapChangedCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addMapChangedPathPlanningCB(ArFunctor functor, int position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedPathPlanningCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position); else AriaJavaJNI.ArMap_addMapChangedPathPlanningCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position);
  }

  public void addMapChangedPathPlanningCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedPathPlanningCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addMapChangedPathPlanningCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remMapChangedPathPlanningCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remMapChangedPathPlanningCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remMapChangedPathPlanningCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addMapChangedLocalizationCB(ArFunctor functor, int position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedLocalizationCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position); else AriaJavaJNI.ArMap_addMapChangedLocalizationCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position);
  }

  public void addMapChangedLocalizationCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addMapChangedLocalizationCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addMapChangedLocalizationCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remMapChangedLocalizationCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remMapChangedLocalizationCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remMapChangedLocalizationCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addPreMapChangedCB(ArFunctor functor, int position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPreMapChangedCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position); else AriaJavaJNI.ArMap_addPreMapChangedCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position);
  }

  public void addPreMapChangedCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPreMapChangedCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addPreMapChangedCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remPreMapChangedCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remPreMapChangedCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remPreMapChangedCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void setMapChangedLogLevel(ArLog.LogLevel level) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setMapChangedLogLevel(swigCPtr, this, level.swigValue()); else AriaJavaJNI.ArMap_setMapChangedLogLevelSwigExplicitArMap(swigCPtr, this, level.swigValue());
  }

  public ArLog.LogLevel getMapChangedLogLevel() {
    return ArLog.LogLevel.swigToEnum((getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapChangedLogLevel(swigCPtr, this) : AriaJavaJNI.ArMap_getMapChangedLogLevelSwigExplicitArMap(swigCPtr, this));
  }

  public void writeToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeToFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeToFunctorSwigExplicitArMap(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void writeObjectsToFunctor(ArFunctor1_CString functor, String endOfLineChars, boolean isOverrideAsSingleScan, String maxCategory) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeObjectsToFunctor__SWIG_0(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, isOverrideAsSingleScan, maxCategory); else AriaJavaJNI.ArMap_writeObjectsToFunctorSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, isOverrideAsSingleScan, maxCategory);
  }

  public void writeObjectsToFunctor(ArFunctor1_CString functor, String endOfLineChars, boolean isOverrideAsSingleScan) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeObjectsToFunctor__SWIG_1(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, isOverrideAsSingleScan); else AriaJavaJNI.ArMap_writeObjectsToFunctorSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars, isOverrideAsSingleScan);
  }

  public void writeObjectsToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_writeObjectsToFunctor__SWIG_2(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars); else AriaJavaJNI.ArMap_writeObjectsToFunctorSwigExplicitArMap__SWIG_2(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void addPreWriteFileCB(ArFunctor functor, ArListPos.Pos position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPreWriteFileCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue()); else AriaJavaJNI.ArMap_addPreWriteFileCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue());
  }

  public void addPreWriteFileCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPreWriteFileCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addPreWriteFileCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remPreWriteFileCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remPreWriteFileCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remPreWriteFileCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addPostWriteFileCB(ArFunctor functor, ArListPos.Pos position) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPostWriteFileCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue()); else AriaJavaJNI.ArMap_addPostWriteFileCBSwigExplicitArMap__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue());
  }

  public void addPostWriteFileCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPostWriteFileCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_addPostWriteFileCBSwigExplicitArMap__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remPostWriteFileCB(ArFunctor functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remPostWriteFileCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor); else AriaJavaJNI.ArMap_remPostWriteFileCBSwigExplicitArMap(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addPreParseFileCB(SWIGTYPE_p_ArFunctor1T_std__string_t functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_addPreParseFileCB(swigCPtr, this, SWIGTYPE_p_ArFunctor1T_std__string_t.getCPtr(functor)); else AriaJavaJNI.ArMap_addPreParseFileCBSwigExplicitArMap(swigCPtr, this, SWIGTYPE_p_ArFunctor1T_std__string_t.getCPtr(functor));
  }

  public void remPreParseFileCB(SWIGTYPE_p_ArFunctor1T_std__string_t functor) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_remPreParseFileCB(swigCPtr, this, SWIGTYPE_p_ArFunctor1T_std__string_t.getCPtr(functor)); else AriaJavaJNI.ArMap_remPreParseFileCBSwigExplicitArMap(swigCPtr, this, SWIGTYPE_p_ArFunctor1T_std__string_t.getCPtr(functor));
  }

  public void forceMapLoadOnConfigProcessFile() {
    AriaJavaJNI.ArMap_forceMapLoadOnConfigProcessFile(swigCPtr, this);
  }

  public boolean readFile(String fileName) {
    return AriaJavaJNI.ArMap_readFile(swigCPtr, this, fileName);
  }

  public boolean writeFile(String fileName) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_writeFile(swigCPtr, this, fileName) : AriaJavaJNI.ArMap_writeFileSwigExplicitArMap(swigCPtr, this, fileName);
  }

  public boolean getMapId(SWIGTYPE_p_ArMapId mapIdOut, boolean isInternalCall) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapId__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArMapId.getCPtr(mapIdOut), isInternalCall) : AriaJavaJNI.ArMap_getMapIdSwigExplicitArMap__SWIG_0(swigCPtr, this, SWIGTYPE_p_ArMapId.getCPtr(mapIdOut), isInternalCall);
  }

  public boolean getMapId(SWIGTYPE_p_ArMapId mapIdOut) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapId__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArMapId.getCPtr(mapIdOut)) : AriaJavaJNI.ArMap_getMapIdSwigExplicitArMap__SWIG_1(swigCPtr, this, SWIGTYPE_p_ArMapId.getCPtr(mapIdOut));
  }

  public boolean calculateChecksum(SWIGTYPE_p_unsigned_char md5DigestBuffer, long md5DigestBufferLen) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_calculateChecksum(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(md5DigestBuffer), md5DigestBufferLen) : AriaJavaJNI.ArMap_calculateChecksumSwigExplicitArMap(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(md5DigestBuffer), md5DigestBufferLen);
  }

  public String getBaseDirectory() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getBaseDirectory(swigCPtr, this) : AriaJavaJNI.ArMap_getBaseDirectorySwigExplicitArMap(swigCPtr, this);
  }

  public void setBaseDirectory(String baseDirectory) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setBaseDirectory(swigCPtr, this, baseDirectory); else AriaJavaJNI.ArMap_setBaseDirectorySwigExplicitArMap(swigCPtr, this, baseDirectory);
  }

  public String getTempDirectory() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getTempDirectory(swigCPtr, this) : AriaJavaJNI.ArMap_getTempDirectorySwigExplicitArMap(swigCPtr, this);
  }

  public void setTempDirectory(String tempDirectory) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setTempDirectory(swigCPtr, this, tempDirectory); else AriaJavaJNI.ArMap_setTempDirectorySwigExplicitArMap(swigCPtr, this, tempDirectory);
  }

  public String createRealFileName(String fileName) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_createRealFileName(swigCPtr, this, fileName) : AriaJavaJNI.ArMap_createRealFileNameSwigExplicitArMap(swigCPtr, this, fileName);
  }

  public String getFileName() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getFileName(swigCPtr, this) : AriaJavaJNI.ArMap_getFileNameSwigExplicitArMap(swigCPtr, this);
  }

  public void setSourceFileName(String sourceName, String fileName, boolean isInternalCall) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setSourceFileName__SWIG_0(swigCPtr, this, sourceName, fileName, isInternalCall); else AriaJavaJNI.ArMap_setSourceFileNameSwigExplicitArMap__SWIG_0(swigCPtr, this, sourceName, fileName, isInternalCall);
  }

  public void setSourceFileName(String sourceName, String fileName) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setSourceFileName__SWIG_1(swigCPtr, this, sourceName, fileName); else AriaJavaJNI.ArMap_setSourceFileNameSwigExplicitArMap__SWIG_1(swigCPtr, this, sourceName, fileName);
  }

  public boolean refresh() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_refresh(swigCPtr, this) : AriaJavaJNI.ArMap_refreshSwigExplicitArMap(swigCPtr, this);
  }

  public void setIgnoreEmptyFileName(boolean ignore) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setIgnoreEmptyFileName(swigCPtr, this, ignore); else AriaJavaJNI.ArMap_setIgnoreEmptyFileNameSwigExplicitArMap(swigCPtr, this, ignore);
  }

  public boolean getIgnoreEmptyFileName() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getIgnoreEmptyFileName(swigCPtr, this) : AriaJavaJNI.ArMap_getIgnoreEmptyFileNameSwigExplicitArMap(swigCPtr, this);
  }

  public void setIgnoreCase(boolean ignoreCase) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setIgnoreCase__SWIG_0(swigCPtr, this, ignoreCase); else AriaJavaJNI.ArMap_setIgnoreCaseSwigExplicitArMap__SWIG_0(swigCPtr, this, ignoreCase);
  }

  public void setIgnoreCase() {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setIgnoreCase__SWIG_1(swigCPtr, this); else AriaJavaJNI.ArMap_setIgnoreCaseSwigExplicitArMap__SWIG_1(swigCPtr, this);
  }

  public boolean getIgnoreCase() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getIgnoreCase(swigCPtr, this) : AriaJavaJNI.ArMap_getIgnoreCaseSwigExplicitArMap(swigCPtr, this);
  }

  public ArMapInfoInterface getInactiveInfo() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInactiveInfo(swigCPtr, this) : AriaJavaJNI.ArMap_getInactiveInfoSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArMapInfoInterface(cPtr, false);
  }

  public ArMapObjectsInterface getInactiveObjects() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getInactiveObjects(swigCPtr, this) : AriaJavaJNI.ArMap_getInactiveObjectsSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArMapObjectsInterface(cPtr, false);
  }

  public ArMapObjectsInterface getChildObjects() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getChildObjects(swigCPtr, this) : AriaJavaJNI.ArMap_getChildObjectsSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArMapObjectsInterface(cPtr, false);
  }

  public ArArgumentBuilder findMapObjectParams(String mapObjectName) {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_findMapObjectParams(swigCPtr, this, mapObjectName) : AriaJavaJNI.ArMap_findMapObjectParamsSwigExplicitArMap(swigCPtr, this, mapObjectName);
    return (cPtr == 0) ? null : new ArArgumentBuilder(cPtr, false);
  }

  public boolean setMapObjectParams(String mapObjectName, ArArgumentBuilder params, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setMapObjectParams__SWIG_0(swigCPtr, this, mapObjectName, ArArgumentBuilder.getCPtr(params), params, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails)) : AriaJavaJNI.ArMap_setMapObjectParamsSwigExplicitArMap__SWIG_0(swigCPtr, this, mapObjectName, ArArgumentBuilder.getCPtr(params), params, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public boolean setMapObjectParams(String mapObjectName, ArArgumentBuilder params) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_setMapObjectParams__SWIG_1(swigCPtr, this, mapObjectName, ArArgumentBuilder.getCPtr(params), params) : AriaJavaJNI.ArMap_setMapObjectParamsSwigExplicitArMap__SWIG_1(swigCPtr, this, mapObjectName, ArArgumentBuilder.getCPtr(params), params);
  }

  public ArArgumentBuilderPtrList getRemainder() {
    long cPtr = (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getRemainder(swigCPtr, this) : AriaJavaJNI.ArMap_getRemainderSwigExplicitArMap(swigCPtr, this);
    return (cPtr == 0) ? null : new ArArgumentBuilderPtrList(cPtr, false);
  }

  public void setQuiet(boolean isQuiet) {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_setQuiet(swigCPtr, this, isQuiet); else AriaJavaJNI.ArMap_setQuietSwigExplicitArMap(swigCPtr, this, isQuiet);
  }

  public boolean parseLine(String line) {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_parseLine(swigCPtr, this, line) : AriaJavaJNI.ArMap_parseLineSwigExplicitArMap(swigCPtr, this, line);
  }

  public void parsingComplete() {
    if (getClass() == ArMap.class) AriaJavaJNI.ArMap_parsingComplete(swigCPtr, this); else AriaJavaJNI.ArMap_parsingCompleteSwigExplicitArMap(swigCPtr, this);
  }

  public boolean isLoadingDataStarted() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isLoadingDataStarted(swigCPtr, this) : AriaJavaJNI.ArMap_isLoadingDataStartedSwigExplicitArMap(swigCPtr, this);
  }

  public boolean isLoadingLinesAndDataStarted() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_isLoadingLinesAndDataStarted(swigCPtr, this) : AriaJavaJNI.ArMap_isLoadingLinesAndDataStartedSwigExplicitArMap(swigCPtr, this);
  }

  public String getMapCategory() {
    return (getClass() == ArMap.class) ? AriaJavaJNI.ArMap_getMapCategory(swigCPtr, this) : AriaJavaJNI.ArMap_getMapCategorySwigExplicitArMap(swigCPtr, this);
  }

  public boolean readFileAndChangeConfig(String fileName) {
    return AriaJavaJNI.ArMap_readFileAndChangeConfig(swigCPtr, this, fileName);
  }

  public void changeConfigMapName(String fileName) {
    AriaJavaJNI.ArMap_changeConfigMapName(swigCPtr, this, fileName);
  }

}
